- alias: sunset_turn_on_outside
  trigger:
    platform: sun
    event: sunset
    offset: "+00:05:00"
  condition: 
    condition: time
    before: "23:00:00"
  action:
    service: homeassistant.turn_on
    entity_id: switch.utomhusswitch_1

- alias: night_turn_off_outside
  trigger: 
    platform: time
    at: "23:00:00"
  action:
    service: homeassistant.turn_off
    entity_id: switch.utomhusswitch_1

- alias: motion_turn_on_vardagsstuga
  trigger:
    platform: state
    entity_id: binary_sensor.rorelse_vardagsstuga_sensor
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.lampa_vardagsstuga_matbord_level

- alias: motion_turn_off_vardagsstuga
  trigger:
    platform: state
    entity_id: binary_sensor.rorelse_vardagsstuga_sensor
    from: 'on'
    to: 'off'
    for:
      minutes: 30
  action:
    service: homeassistant.turn_off
    entity_id: light.lampa_vardagsstuga_matbord_level

- alias: motion_turn_on_kitchen
  trigger:
    platform: state
    entity_id: binary_sensor.rorelse_koket_sensor
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.dubbelbrytare_koket_switch_3

- alias: motion_turn_on_pannrum
  trigger:
    platform: state
    entity_id: binary_sensor.rorelse_pannrummet_sensor
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.pannrummet_switch

- alias: motion_turn_off_pannrum
  trigger:
    platform: state
    entity_id: binary_sensor.rorelse_pannrummet_sensor
    from: 'on'
    to: 'off'
    for:
      seconds: 30
  action:
    service: homeassistant.turn_off
    entity_id: switch.pannrummet_switch

- alias: open_turn_on_pannrum_outside
  trigger:
    platform: state
    entity_id: binary_sensor.dorr_pannrummet_sensor
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.pannrummet_switch_3

- alias: close_turn_off_pannrum_outside
  trigger:
    platform: state
    entity_id: binary_sensor.dorr_pannrummet_sensor
    from: 'on'
    to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: switch.pannrummet_switch_3

- alias: motion_turn_on_garage
  trigger:
    - platform: state
      entity_id: binary_sensor.rorelse_garaget_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.dorr_garaget_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.dorr_bryggarhuset_sensor
      from: 'off'
      to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.bryggarhuset_lysror_switch

- alias: motion_turn_off_garage
  trigger:
    platform: state
    entity_id: binary_sensor.rorelse_garaget_sensor
    to: 'off'
    for:
      minutes: 1
  condition:
    condition: state
    entity_id: binary_sensor.dorr_garaget_sensor
    state: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: switch.bryggarhuset_lysror_switch

