homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret location_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  elevation: !secret location_elevation

  # metric for Metric, imperial for Imperial
  unit_system: metric
  time_zone: Europe/Stockholm
  
  customize: !include_dir_merge_named customize/

# Push notifications
notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

# Netatmo weather station
netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enables http connection, SSL is done through nginx
http:
  server_port: !secret http_port
  api_password: !secret http_password

# Checks for available updates
updater:
  include_used_components: true

# Influx DB for export to for example Graphana
influxdb: !include influx.yaml

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history: !include history.yaml

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

group: !include_dir_merge_named groups/
automation: !include automations.yaml

# Tellstick
tellstick:
  signal_repetitions: 5

sensor: !include sensors.yaml
binary_sensor:
  - platform: template
    sensors:
      rorelse_garage:
        device_class: motion
        friendly_name: "Rörelse garaget"
        value_template: >-
          {{ states('sensor.rorelse_garaget_burglar')|float > 0 }}

zwave: !include zwave.yaml

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  agent_user_id: !secret google_assistant_user_id
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light

